#!/bin/bash

set -x

git clone --depth 1 git@github.com:u-root/u-root
go work init u-root
# git clone --depth 1 git@github.com:k3s-io/k3s.git
git clone --depth 1 git@github.com:containerd/containerd
git clone --depth 1 git@github.com:coredns/coredns.git
git clone --depth 1 git@github.com:etcd-io/etcd.git
git clone --depth 1 -b purego git@github.com:u-root/flannel
git clone --depth 1 -b purego git@github.com:u-root/runc

set -e
(cd containerd && go mod tidy)
(cd coredns && go mod tidy)
(cd etcd/etcdctl && go mod tidy)
(cd flannel && go mod tidy)
(cd runc && go mod tidy)
(cd u-root && go mod tidy && GOARCH= GOOS= go build)
./u-root/u-root -o initramfs.cpio u-root/cmds/core/* runc/ ./containerd/cmd/containerd ./flannel ./coredns ./etcd/etcdctl

